export default {
    'LOGIN_ATTEMPT': 'LOGIN_ATTEMPT',
    'LOGIN_SUCCESS': 'LOGIN_SUCCESS',
    'LOGIN_FAILURE': 'LOGIN_FAILURE',

    'LOGOUT_ATTEMPT': 'LOGOUT_ATTEMPT',
    'LOGOUT_SUCCESS': 'LOGOUT_SUCCESS',
    'LOGOUT_FAILURE': 'LOGOUT_FAILURE',

    'ROUTE_WELCOME':   'ROUTE_WELCOME',
    'ROUTE_DASHBOARD': 'ROUTE_DASHBOARD',
};